import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    comp1text: {
      fontSize: 25,
      color: 'grey',
      fontWeight: '500',
      marginLeft: 10,
      marginRight: 10,
    },
    comp1textpn: {
      fontSize: 35,
      fontWeight: 'bold',
      marginLeft: 15,
      color: 'black',
    },
    infocontainer: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      backgroundColor: 'white',
      padding: 20,
      borderRadius: 10,
      marginTop: 10,
      marginLeft: 10,
      marginRight: 10,
      shadowColor: 'black',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
    },
    infocontainer1: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      backgroundColor: 'white',
      padding: 20,
      borderRadius: 10,
      marginTop: 10,
      marginLeft: 10,
      marginRight: 10,
      shadowColor: 'black',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
    },
    timing: {
      color: 'black',
      fontWeight: 'bold',
      fontSize: 25,
    },
    infocontainer2: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'white',
      padding: 30,
      borderRadius: 10,
      marginTop: 10,
      marginLeft: 10,
      marginRight: 10,
      shadowColor: 'black',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
    },
    infocontainer3: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'white',
      padding: 30,
      borderRadius: 10,
      marginTop: 10,
      marginLeft: 10,
      marginRight: 10,
      shadowColor: 'black',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
    },
    header: {
      color: 'black',
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 25,
    },
    statsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    stat: {
      alignItems: 'center',
      justifyContent: 'space-between',
      flex: 1,
    },
    value: {
      color: 'grey',
      fontSize: 18,
      fontWeight: 'bold',
    },
    label: {
      color: 'grey',
      fontSize: 12,
    },
});

export default styles;